### ISSUE TITLE
Alienware 15 R3 Fixes

### ISSUE THREAD

**Issue by RastaManKing** [rsm-gh/akbl#53]
Distribution name: Arch Linux
Distribution version: 4.18.16-arch1-1-ARCH
Python version: Python 3.7.1
akbl version: v2018.11.03
Computer model: Alienware 15 R3

Application runs and can turn lights on and off and zones are correct,
but colors are not, blue color in akbl displays green in leds..
white in akbl displays orange in leds, etc..

**Comment by RastaManKing** [comment]
> hi @RastaManKing that's actually a known bug since the `DATA_LENGTH` variable was specially modified for this computer (`value = 12 instead of 9`).
> 
> Since [the other thread](https://github.com/rsm-gh/akbl/issues/8) has too much information, I'm gonna close it and I'll let this one open.
> 
> And to be honest, this may take some time to fix. I have many improvements to do to the software and fixing this kind of bugs without having a Alienware 15R3 in my possession is kinda annoying.
> 
> -rsm

i understand, your work is still very much apretiated, i am able to turn lights on/off, keep zones on.. and that is very much needed, choosing colors is secondary.. i can stick with green :)
thanks fo your work. i have alienware 15 R3, if you need help, let me know.

**Comment by josedellabosca** [comment]
Is data lenght "12" ok, or it should be "c" since it's an hexadecimal value?

**Comment by rsm-gh** [comment]
@josedellabosca some time ago I checked if integers worked as same as hex values and they seem to do it. Since then I converted almost all the hex in to integers for readability

**Comment by rsm-gh** [comment]
@josedellabosca to do that you need a fully understanding of the software and the packages that are sent into the USB device. Sometime ago I started doing that work but since everything works on my computer I drop it. With the time I've been improving the software architecture and the documentation so more people get involved since I won't be fore ever doing the maintenance and helping other people!

**Comment by RastaManKing** [comment]
> @josedellabosca to do that you need a fully understanding of the software and the packages that are sent into the USB device. Sometime ago I started doing that work but since everything works on my computer I drop it. With the time I've been only improving the software architecture and the documentation so more people get involved, but the main core of the software/hardware I've been skipping it since it requires a lot of time and effort.

if you point me in the right direction(documentation and software to capture usb packets, wireshark with a plugin or something i imagine?) ill be willing to spend some time and analyze this :)

**Comment by rsm-gh** [comment]
@RastaManKing I actually haven't really invested my self in to the hardware part since I took that from pyAlienFx. Here's what can I tell you:

- For understanding the code for creating the USB packages you must read the "Engine" module.
- For debugging your modifications, activate the debug mode `/akbl/usr/lib/python3/AKBL/utils.py` and to use the block testing window. 
- For sniffing packages, I actually ignore if that's possible to do. Anyways if you find a way to do it, probably the best would be to do it on windows by using the windows software. That could allow us to compare the packages and solve most of the problems.

I'll try to add much more documentation and explanation to this in the website.

**Comment by josedellabosca** [comment]
Or we can try asking nicely to Dell for the info.

**Comment by rsm-gh** [comment]
@josedellabosca the main pyAlienFx developer told me that dell never responded his messages. You can contact them but I doubt that they will respond and give you any info.

**Comment by josedellabosca** [comment]
Yes , i tried to talk to Dell but they were very rude.
For sniffing the USB i'am using this :https://github.com/djpnewton/busdog

here is an example
https://pasteboard.co/HTxmawh.png

**Comment by buzyn** [comment]
Добрый день. вы решили проблему с цветами? у Вас на windows тоже цвета неправильно отображаются?
на моем alienware 13, синяя подсветка логотипа работает в половину мощности. ничего не помогает

**Comment by rsm-gh** [comment]
I'm gonna close this since the colors problems will be tracked [here](https://github.com/rsm-gh/akbl/issues/65).
