### ISSUE TITLE
Help on install: Fedora 33

### ISSUE THREAD

**Issue by ironstarfish** [rsm-gh/akbl#87]
# System information

+ Distribution name: Fedora
+ Distribution version: Fedora 33 Workstation
+ Python3 version: 3.7.9
+ akbl version: latest pull from github
+ Computer model: Alienware 15 R1
+ Daemon status: N/A

Tried to install this on Fedora 33, installation seems to go smoothly.  Installed dependencies but failed on the following:
libgtk-3-0 libgtk-3-dev gir1.2-appindicator3-0.1 gir1.2-appindicator3 python3-gi python3-usb python3-pyro4

When I try to run the app, I get this message:
Traceback (most recent call last):
  File "/usr/share/AKBL/launch/commands.py", line 22, in <module>
    from AKBL.Bindings import Bindings
ModuleNotFoundError: No module named 'AKBL'

Is it possible to use this on Fedora? Are there instructions for installing dependencies?
I was able to use this on Ubuntu before and it works fine.

**Comment by rsm-gh** [comment]
Hello,

akbl can be used in any gnu/linux distro, but since I don’t use fedore I can not guide you for the installation. 

Currently you are facing two problems, a failed python installation, and a problem with the dependencies.

The message ‘no module AKBL found’ shows the python problem. Verify that when installing akbl, you have a setup message for python 3.7. And if you do, verify that you have the akbl module into `/usr/lib/python3/AKBL`, and a shortcut into the equivalent of the python3.7 folder.

Once the python module correctly installed, you will have to find the name of the dependencies, which are probably pretty similar to the ones I use for ArchLinux. You can check them in the installation page.

Good luck with that, if you need more help you will have to wait somme weeks until I have my computer.

rsm~

**Comment by ironstarfish** [comment]
Looks like this is caused by Anaconda being the default python instance.  I changed the default instance in .bashrc and setup went through fine and was able to configure the app.  Hopefully there is a way to install the required libraries in anaconda.  I was having problems with gi and gtk3 while trying to make this work with anaconda.
